### ISSUE TITLE
SpatExtent argument

### ISSUE THREAD

**Issue by rhijmans** [riatelab/maptiles#1]
It would by to have allow argument `x` in `get_tiles`  to be a  `SpatExtent`.  You could do something like this:
 
```
if (inherits(x, "SpatExtent")) {
	bbx <- as.vector(e)[c(1,3,2,4)]
} else {
```

I would prefer that over a `SpatRaster` argument, but you could do something like this 

```
} else if (inherits(x, "SpatRaster")) {
   p <- as.polygons(ext(x), crs=crs(x))
   y <- project(p, "epsg:4326")
   bbx <- as.vector(ext(y))[c(1,3,2,4)]
```

**Comment by rCarto** [comment]
Good idea, I've added support for `bbox` and `SpatialExtent` objects. f06260c
