### ISSUE TITLE
 Timeout was reached:

### ISSUE THREAD

**Issue by bergest** [riatelab/maptiles#11]
hi
at work I can't use maptiles, while at home, there is no problem
I always have the error while with ggmap I have no problem 

Error in curl::curl_download(url = q, destfile = outfile) : 
  Timeout was reached: [] Connection timed out after 10009 milliseconds

I have indicated the proxy with 
library(httr)
set_config(.........) 

For maptiles at work, is it the proxy ? And how to fix it? 

Thank you for your help

**Comment by rCarto** [comment]
Hello, 
I must admit that I don't know much about proxies. 
`maptiles` does not use `httr`, I don't think it is relevant to use `set_config()`. 
Maybe you can find something useful here: https://stackoverflow.com/Questions/6467277/proxy-setting-for-r
Note that many answers suggests OS dependent solutions.  
Anyway, if you find that something should be changed inside the package to ease its usage with a proxy don't hesitate to tell me.

**Comment by rCarto** [comment]
See #12
