### ISSUE TITLE
Error in png::readPNG(img) : file is not in PNG format

### ISSUE THREAD

**Issue by gremms1** [riatelab/maptiles#13]
Hello,

I am trying to get the following code to work, but it's not working out:

```
library(sf)
library(maptiles)

p = st_point(c(110784.2,494605.3))
p = st_sfc(p)
p = st_set_crs(p, 28992)
bb = st_bbox(st_buffer(p, 300))

url <- "https://geodata.nationaalgeoregister.nl/tiles/service/wmts/opentopo/EPSG:28992/{z}/{x}/{y}.png"
mffp <- list(src="OpenTopo", q=url, sub=NA, cit='')

t <- get_tiles(bb, provider=mffp, crop= T, forceDownload = T, zoom=5)
```
I get the following error: `Error in png::readPNG(img) : file is not in PNG format`
The strange this is that entering the following url in my browser does yield the correct tile:
`https://geodata.nationaalgeoregister.nl/tiles/service/wmts/opentopo/EPSG:28992/5/16/12.png`
So the error that it throws me seems strange.

**Comment by rCarto** [comment]
Hello, 
I've tried to save this tile (right-click, save):
https://geodata.nationaalgeoregister.nl/tiles/service/wmts/opentopo/EPSG:28992/5/16/12.png
and saw that the file is actually a **jpeg** despite its **png** extension. 

So I tried this url for the tile server:
```r
url <- "https://geodata.nationaalgeoregister.nl/tiles/service/wmts/opentopo/EPSG:28992/{z}/{x}/{y}.jpeg"
```
but `maptiles` does not understand **jpeg** extension, only **jpg** and **png**. 
So I've update `maptiles` to allow **jpeg** extension and you can try this (using the dev version of the package):
```r
remotes::install_github('riatelab/maptiles')
```
``` r
library(sf)
#> Linking to GEOS 3.9.0, GDAL 3.2.2, PROJ 7.1.0; sf_use_s2() is TRUE
library(maptiles)

p = st_point(c(328452.9,267552.5))
p = st_sfc(p)
p = st_set_crs(p, 28992)
bb = st_bbox(st_buffer(p, 300000))

url <- "https://geodata.nationaalgeoregister.nl/tiles/service/wmts/opentopo/EPSG:28992/{z}/{x}/{y}.jpeg"
mffp <- list(src="OpenTopo", q=url, sub=NA, cit='')

t <- get_tiles(bb, provider=mffp, crop= T, forceDownload = T, zoom=7)
plot_tiles(t, adjust = TRUE)
```

![](https://i.imgur.com/0onOeTr.png)

<sup>Created on 2022-02-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I have modified point coordinates and zoom level from your original example to show something not on the sea :-)

**Comment by gremms1** [comment]
Hi, I came to the same conclusion (concerning the jpeg) yesterday evening! Thanks for acting so promptly. Getting the tiles now works, the only thing I can´t figure out is what is going wrong with the projection. Using the following code 
```
library(sf)
library(maptiles)
library(stars)
library(tmap)
p = st_point(c(328452.9,267552.5))
p = st_sfc(p)
p = st_set_crs(p, 28992)
bb = st_bbox(st_buffer(p, 300000))
url <- "https://geodata.nationaalgeoregister.nl/tiles/service/wmts/opentopo/EPSG:28992/{z}/{x}/{y}.jpeg"
mffp <- list(src="OpenTopo", q=url, sub=NA, cit='')
t <- get_tiles(bb, provider=mffp, crop= T, forceDownload = T, zoom=7)
plot_tiles(t, adjust = TRUE)
map <- stars::st_as_stars(t)
tmap_mode("plot")
tm_shape(map) +
  tm_rgb() +
tm_graticules(lines=F)
```
shows that the map is way bigger than it actually should be.

**Comment by rCarto** [comment]
I suspected something odd with the projection stuff. 
I think it has something to do with this part of the url (and the way tiles are delivered): EPSG:28992
Most of tiles providers ask for lon & lat in EPSG:4326 and offer tiles in EPSG:3857 (web mercator) and this projs are actually hardcoded in `maptiles`.
Can you direct me to the API documentation just to be sure of what input/output proj are expected?

**Comment by gremms1** [comment]
I think you're right. [this](https://geodata.nationaalgeoregister.nl/tiles/service/wmts?request=GetCapabilities) is the KVP WMTS GetCapabilities page. If you ctrl+f and search for opentopo you can see <TileMatrixSet>EPSG:28992. Thanks for your help!

**Comment by gremms1** [comment]
Additionally, here a working example with an interactive tmap (requires dev-version):
```
remotes::install_github('r-tmap/tmap')
library(tmap)
library(leaflet)
epsg28992 <- leafletCRS(
  crsClass = "L.Proj.CRS"
  ,code = "EPSG:28992"
  ,proj4def = "+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.417,50.3319,465.552,-0.398957,0.343988,-1.8774,4.0725 +units=m +no_defs"
  ,origin=c(-285401.92,903401.92)
  ,resolutions = c(3251.206502413005,1625.6032512065026,812.8016256032513,406.40081280162565,203.20040640081282,101.60020320040641, 50.800101600203206,25.400050800101603,12.700025400050801,6.350012700025401,3.1750063500127004,1.5875031750063502,0.7937515875031751,0.39687579375158755,0.19843789687579377,0.09921894843789689,0.04960947421894844)
)

url <- "https://geodata.nationaalgeoregister.nl/tiles/service/wmts/opentopo/EPSG:28992/{z}/{x}/{y}.jpeg"


data(World)
tmap_mode("view")

tm_shape(World) +
  tm_polygons() +
  tm_basemap(NULL) +
  tm_view(projection = epsg28992, set.view = c(5.092098,52.093992,4)) +
  tm_tiles(server = url) +
  tm_mouse_coordinates() 
```
