### ISSUE TITLE
tiles look unsharp, even with adjust = TRUE

### ISSUE THREAD

**Issue by mtennekes** [riatelab/maptiles#15]
![Screenshot from 2022-03-01 18-54-54](https://user-images.githubusercontent.com/2444081/156230380-61507ce6-6808-4932-a4b9-d8d4e8ebcfea.png)
 
I have no clue why: maybe the OS, the graphics device, ...

```r
─ Session info  ─────────────────────────────────────────────────────────────────────────────────────────
 hash: person playing handball: medium-light skin tone, breast-feeding: light skin tone, flag: Curaçao

 setting  value
 version  R version 4.1.2 (2021-11-01)
 os       Ubuntu 20.04.4 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Europe/Amsterdam
 date     2022-03-01
 rstudio  1.4.1714 Juliet Rose (desktop)
 pandoc   NA
``` 

(https://github.com/r-tmap/tmap/issues/603)

**Comment by rCarto** [comment]
Original tiles use EPSG:3857. In most cases `get_tiles()` uses the projection of its x argument to reproject the tiles.
To avoid any deformation induced by the reprojection process you can use EPSG:3857 for x.

**Comment by mtennekes** [comment]
Thanks! It is much better, but I also had problems with RStudio. After the update, the graphics device looks sharper.
