### ISSUE TITLE
Getting error when running example : unable to find an inherited method for function ‘crs’ for signature ‘"character"’

### ISSUE THREAD

**Issue by amygimma** [riatelab/maptiles#26]
Hello, 

I tried running the example for the get_tiles function, and I'm getting the following error when calling `get_tiles` on lines 4 and 15: 

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘crs’ for signature ‘"character"’

```
library(sf)
library(maptiles)
nc <- st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)
nc_osm <- get_tiles(nc, crop = TRUE, zoom = 6)
plot_tiles(nc_osm)

# Download tiles from OSM, no labels
osm <- list(
  src = 'OSM',
  q = '"http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"',
  sub = c('a','b', 'c'),
  cit = '© OpenStreetMap contributors.'
)
# dowload tiles and compose raster (SpatRaster)
nc_osm2 <- get_tiles(x = nc, provider = osm, crop = TRUE,
                     zoom = 6, verbose = TRUE)
# Plot the tiles
plot_tiles(nc_osm2)
```

I'm running on windows and tried updating the packages - though I haven't updated all dependencies. It feels like it's probably a local environment issue, but I'm not sure how to approach problem solving. Any recommendations?

**Comment by rCarto** [comment]
Hello,
Well, my recommendation would be to update all dependencies if it's possible.

**Comment by rCarto** [comment]
Also, from the code of the example you have provided, I strongly suspect that you are not using the last version of `maptiles` (0.6.1).
There is now a provider constructor thanks to the `create_provider()` function.

**Comment by ochee** [comment]
Hello,
Have the same problem as @amygimma : get_tiles function render an an error


```
library(sf)
library(maptiles)
# import North Carolina counties
nc <- st_read(system.file("shape/nc.shp", package="sf"),
              quiet = TRUE)
Linking to GEOS 3.10.2, GDAL 3.4.1, PROJ 8.2.1; sf_use_s2() is TRUE
nc_osm <- get_tiles(nc, crop = TRUE)
```

> Error in (function (classes, fdef, mtable)  :
>   unable to find an inherited method for function ‘crs’ for signature ‘"character"’
> 

I updated maptiles and sf packages and dependencies, without succes. Below, my sessionInfo :
```
sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] maptiles_0.7.0 sf_1.0-8

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10        magrittr_2.0.3     units_0.8-0        tidyselect_1.2.0
 [5] R6_2.5.1           rlang_1.1.1        fansi_1.0.4        dplyr_1.1.2
 [9] tools_4.1.2        grid_4.1.2         KernSmooth_2.23-20 utf8_1.2.3
[13] terra_1.6-17       cli_3.6.1          e1071_1.7-12       DBI_1.1.3
[17] class_7.3-20       tibble_3.2.1       lifecycle_1.0.3    codetools_0.2-18
[21] vctrs_0.6.3        glue_1.6.2         proxy_0.4-27       compiler_4.1.2
[25] pillar_1.9.0       generics_0.1.3     classInt_0.4-8     pkgconfig_2.0.3
```

Many thanks for your help

**Comment by rCarto** [comment]
Hello, in your case I would update R itself if it's possible. The current version is 4.3.3 and the 4.4 will be out at the end of the month. 
terra is currently at 1.7-71 and sf at 1.0-16
