### ISSUE TITLE
Error while trying to access a vector map served by self-hosted Tileserver-GL

### ISSUE THREAD

**Issue by asitemade4u** [riatelab/maptiles#32]
Hi,
- So, I have installed the development version of `maptiles`.
- I have a Tileserver-GL vector tile server installed on one of our servers. I know it works because I am able to access and display the tiles it serves in QGis, by pointing to its `xyz` address: `http://<IP_address>:8088/data/nycblg/{z}/{x}/{y}.pbf`
- Now, I am trying to access the tiles served by Tileserver-GL using `maptiles`. It fails with an error.

Here is my code:

```R
# Define provider
tlsplc <- maptiles::create_provider(name = "nycplc", url = "http://<ip_address>:8088/data/nycplc/{z}/{x}/{y}.pbf", citation = "kuq, 2024")
# Create extent from shapefile (counties)
nysshp <- sf::st_read("gis/county.shp", quiet = TRUE)
# Draw vector tiles
nycplc <- maptiles::get_tiles(x = nysshp, provider = tlsplc, crop = FALSE, zoom = 12, project = FALSE, verbose = TRUE)
```
The error I get is:

```error
Zoom: 12
Source(s): kuq, 2024
Cache directory: /tmp/RtmpXX5urU/nycplc
Error in as.vector(x, "character") : cannot coerce type 'closure' to vector of type 'character'
```
What am I missing here?
S.

**Comment by rCarto** [comment]
maptiles does not work for vector tiles, only raster.

**Comment by asitemade4u** [comment]
Hi @rCarto , 
not to interfere with your priorities, but with the advent of widely available open-source and free vector maps, thanks to [Overture Maps](hhttps://github.com/OvertureMaps), I think you should consider them for `maptiles`.
In any case, would you have a recommendation for a R package able to deal with vector maps served by Tileserver-GL?
Thanks in advance,
S.

**Comment by rCarto** [comment]
`protolite`?

**Comment by asitemade4u** [comment]
Thanks, will try it.
