### ISSUE TITLE
Increase quality of images/maptiles

### ISSUE THREAD

**Issue by cutterkom** [riatelab/maptiles#33]
Hey, 

great plugin! It really solves my problem to combine base map from tile servers with ggplot2 functionalities. 

But I see one downside right now: The quality of the maptiles is worse than e.g. using leaflet. Why is that? And can I improve the image quality? 

In the end I want to use satelitte tiles and it really does not look good like that. 

An example:

```R
library(sf)
library(maptiles)
library(tidyverse)
library(tidyterra)

nc <- st_read(system.file("shape/nc.shp", package="sf"), 
              quiet = TRUE)
nc_osm <- get_tiles(nc, crop = TRUE)
ggplot() +
 tidyterra::geom_spatraster_rgb(data = nc_osm) + 
  geom_sf(data=nc, color = points_color, size = 1, alpha = 0.7) +
  theme_void()

```

**Comment by rCarto** [comment]
You could use the native tile projection (https://github.com/riatelab/maptiles?tab=readme-ov-file#projection), or increase the zoom level, or export a map with dimensions that fit the ones of your tiles.
