### ISSUE TITLE
add tiles providers

### ISSUE THREAD

**Issue by rCarto** [riatelab/maptiles#4]
https://www.xyht.com/spatial-itgis/using-openstreetmap-basemaps-qgis-3-0/

**Comment by rCarto** [comment]
Wow, that's a huge list!
I'm not sure we should add all these providers. I would for example exclude local maps (Singapore, France, Austria...). But I'm open to discussion. 
I think the use of APIs with token or keys implies some ad-hoc code modification for each provider involved, that may be challenging.

**Comment by dieghernan** [comment]
Agree, I won't include all, and speciallt those that use 2 keys (ID + APIKEY) may require some changes on the function.


I already implemented and checked 39 of them, feel free to add the ones that you like:

https://github.com/dieghernan/cartography/blob/c65adf6f136d6b4733d88266e0af0474837a4a45/R/getTiles.R#L647-L886

Note that a modification on the function is needed, as some times the image extension is not in the url. So for that I added a new `ext` param to the list and changed a bit the code:

https://github.com/dieghernan/cartography/blob/c65adf6f136d6b4733d88266e0af0474837a4a45/R/getTiles.R#L146-L149


Full list of new providers with some notes. I added a note to those that for sure are locals, about the rest I haven't completely checked.

* OpenStreetMap.CH
* OpenStreetMap.BZH
* OpenSeaMap
* OpenPtMap
* OpenRailwayMap
* USGS
* USGS.USTopo
* USGS.USImagery
* USGS.USImageryTopo
* Esri.WorldPhysical
* FreeMapSK [local]
* MtbMap
* SafeCast
* Jawg.Streets (with key)
* Jawg.Terrain (with key)
* Jawg.Sunny (with key)
* Jawg.Dark (with key)
* Jawg.Light (with key)
* Jawg.Matrix (with key)
* WaymarkedTrails.hiking
* WaymarkedTrails.cycling
* WaymarkedTrails.mtb
* WaymarkedTrails.slopes
* WaymarkedTrails.riding
* WaymarkedTrails.skating
* CyclOSM
* Stadia.AlidadeSmooth
* BasemapAT.basemap [local]
* BasemapAT.grau [local]
* BasemapAT.overlay [local]
* BasemapAT.terrain [local]
* BasemapAT.surface [local]
* BasemapAT.highdpi [local]
* BasemapAT.orthofoto [local]
* nlmaps.standaard [local]
* nlmaps.pastel [local]
* nlmaps.grijs [local] 
* NLS

**Comment by dieghernan** [comment]
I haven't tested that but `HEREv3` (not `HERE`) may be included too with an API key only.

**Comment by dieghernan** [comment]
HEREv3 included and tested, and they look real good:


https://github.com/dieghernan/cartography/blob/64fad6b9af8dae64f02dbc028a4ae8529ed37507/R/getTiles.R#L897-L1065



* HEREv3.normalDay
* HEREv3.normalDayCustom
* HEREv3.normalDayGrey
* HEREv3.normalDayMobile
* HEREv3.normalDayGreyMobile
* HEREv3.normalDayTransit
* HEREv3.normalDayTransitMobile
* HEREv3.normalNight
* HEREv3.normalNightMobile
* HEREv3.normalNightGrey
* HEREv3.normalNightGreyMobile
* HEREv3.normalNightTransit
* HEREv3.normalNightTransitMobile
* HEREv3.reducedDay
* HEREv3.reducedNight
* HEREv3.basicMap
* HEREv3.mapLabels
* HEREv3.trafficFlow
* HEREv3.carnavDayGrey
* HEREv3.hybridDay
* HEREv3.hybridDayMobile
* HEREv3.hybridDayTransit
* HEREv3.hybridDayGrey
* HEREv3.pedestrianDay
* HEREv3.pedestrianNight
* HEREv3.satelliteDay
* HEREv3.terrainDay
* HEREv3.terrainDayMobile

**Comment by rCarto** [comment]
- Use [`leaflet.providers`](https://github.com/rstudio/leaflet.providers) directly,  see https://github.com/r-tmap/tmap/issues/603

**Comment by tim-salabim** [comment]
There's thoughts on porting https://github.com/geopandas/xyzservices to R... Interested?

**Comment by rCarto** [comment]
`create_provider()` and changes to the API key management should make it easier to use new providers. I prefer to keep a short list of built-in providers to avoid tedious maintenance.
